### ISSUE TITLE
Which project result do you think is better?

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/dcscn-super-resolution#1]
Comparing with this project https://github.com/jiny2001/deeply-recursive-cnn-tf ? Which result for 4x is better? By eyes and by PSNR? Thank.

**Comment by jiny2001** [comment]
Well, I believe this DCSCN can get better results than the Deeply Recursive CNN. Using x8 augmented (yang91 + BSD200) dataset as training data and 10 CNN layers with 196 to 48 filters in feature extraction network, I could get those PSNR results for x4. Set5:31.47 Set14:28.12 BSD100:27.33. I will check my DRCN clone's result later though.

**Comment by jiny2001** [comment]
Sorry for late reply but the experiment took almost 2 days. I tried with my DRCN implementation with x4 augmented (yang91 + general100) dataset. And the result was Set5:30.91 Set14:27.76 BSD100:27.09, it means DCSCN had better performance than my DRCN clone in this case. I know 8x (yang91+bsd200) can lead a better performance than 4x (yang91+general100), I can say DCSCN can learn much faster (it only takes 5hours to train) than DRCN and the performance will be same or better than my DRCN clone.

**Comment by GabrielLin** [comment]
Thanks for your result, it helps a lot. I will try this project later.
