### ISSUE TITLE
Non-boolean argument to boolean flag

### ISSUE THREAD

**Issue by phqmourao** [jiny2001/dcscn-super-resolution#11]
https://github.com/jiny2001/dcscn-super-resolution/blob/12f81b6565a99c8d23bf506ba78e01a2ad16d945/helper/args.py#L74

Hi,
I think it should be:
flags.DEFINE_integer("save_images_num", 10, "Number of CNN images saved")
Thanks

**Comment by jiny2001** [comment]
Yes, you are totally right.

Thank you!!
