### ISSUE TITLE
Syntax error message.

### ISSUE THREAD

**Issue by ontheway16** [jiny2001/dcscn-super-resolution#12]
Hi I am new to this and trying to figure out how to apply to a sample image. I am receiving the following error;

```
$ python sr.py --file image001.png --dataset yang_bsd_4 --filters_decay_gamma 1.5 
Traceback (most recent call last):
  File "sr.py", line 11, in <module>
    import DCSCN
  File "/home/user01/Downloads/dcscn-super-resolution-master/DCSCN.py", line 20, in <module>
    from helper import loader, utilty as util
  File "/home/user01/Downloads/dcscn-super-resolution-master/helper/loader.py", line 137
    print('.', end='', flush=True)
                  ^
SyntaxError: invalid syntax
```

**Comment by jiny2001** [comment]
Hi, I believe this is a python version issue.

Which python version are you using?
If it's not 3.6, you can update it and try it again?

**Comment by ontheway16** [comment]
Hi Jin,
Thanks for the quick response. My python version is 2.7.6. In fact, I am mainly using Nvidia DIGITS framework and I am not sure whats happens to DIGITS, if I update it to 3.x.x

**Comment by jiny2001** [comment]
Hi,
In that case, you can comment out the line.
The line just shows the progress of loading.

I'm afraid there maybe some python 3.x dependency though...

**Comment by ontheway16** [comment]
I will try, thank you. Have another question in mind but I couldnt decide asking here or open a new issue.
Here it goes;
I am not very familiar with how srGAN solutions work. My question is, if the model is trained only with certain type of objects (lets say, cars), may it produce better (then current) results, when tested with LR car images?

**Comment by jiny2001** [comment]
Hi, I don't think you need to open a issue if it's just a question.

Just send me and ask. :)

Generally, I believe you can get a better performance when you use more cars for training. Features and knowledge for cars will have more weight on the training phase.

However, there is a suitable model size for each task and using other images may contribute to generalize your model. I'm not sure how effective that method is. And also you should be careful to build a training dataset. 

I believe it will have a better performance when you trained with the specific objects with enough quality and amount of images.

Best,

**Comment by ontheway16** [comment]
This is great because I do not need to generalize the training, instead, I want to focus and enhance only a single (distinct) type of object within whole picture.

In my case, the good;
I have more then 50K of high quality object samples and all unique. Also, both training objects and sr-applied objects are on a (almost) solid-color background. So there will be not much around, other then target objects.

The bad;
Objects that need SR are around/less then 50 pixels in dimensions. They are so small. Not sure if there are parameters to play with, in the model to get better results with smaller portions, or theres a resolution hard limit for enhancement.

Regards,

Alp

**Comment by jiny2001** [comment]
Yeah small images are not good since your receptive field of CNN model would be very big.

But it sounds like worth trying. Actually if you already have images just go and adjust some hyper parameters.

Cheers!
