### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#14]
when trying to train, i get a error from configparser.py "ValueError: invalid literal for int() with base 10: '255.0'. with that i get a error on \helper\loader.py line 259
![image](https://user-images.githubusercontent.com/26292862/38317337-72b2bbd8-37f2-11e8-980a-280868cf2792.png)

**Comment by rafariva** [comment]
modify configparser.py
![image](https://user-images.githubusercontent.com/26292862/38318108-3be5178e-37f4-11e8-8695-e8dcb6e9b4d6.png)

**Comment by jiny2001** [comment]
Hi, thank you for your report.

I didn't think of the case that the max-value arg is float. Thx.

configparser.py is from official python module so you would not better modify it. 

I believe modifiy from
config.getint("batch", "max_value")
to
config.getfloat("batch", "max_value")
in my code is the better way. I'll modify that and upload soon.

Best,

**Comment by rafariva** [comment]
oh thanks, good idea. i will try you adviced change to getfloat
