### ISSUE TITLE
I don't understand why strides=[stride, stride, 1, 1]

### ISSUE THREAD

**Issue by Zamirquito** [jiny2001/dcscn-super-resolution#17]
https://github.com/jiny2001/dcscn-super-resolution/blob/7ecffbe209df46380fc4dfe16574522ef32039ad/DCSCN.py#L333

the params of stides is the stride of the sliding window for each dimension of input, I have read the code about your input, your input is [batch_num, h, w, channel], so the strides should be [1, stride, stride, 1]?

**Comment by jiny2001** [comment]
Hi Zamirquito,

Yes!. it should be [1, stride, stride, 1].
This is a really awful bug. But I always used with stride=1, so I haven't noticed until you tell that.

It was lucky that the stride is always 1 so the result won't change not at all. Thank you to let me know. I fixed.
