### ISSUE TITLE
wrong Training Path

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#18]
Are line 38 and 41 alright?  i am a little confuse traying to train with new images

![image](https://user-images.githubusercontent.com/26292862/38828898-11151b02-417d-11e8-98b1-54cca06686a1.png)

**Comment by jiny2001** [comment]
Hi, I believe that line is correct.

FLAGS.data_dir is by default, "data". And FLAGS.test_dataset is the name of the directory which is under "data" directory and contains your image files for testing performance during training.

**Comment by rafariva** [comment]
thanks. i got it
