### ISSUE TITLE
x2 scale

### ISSUE THREAD

**Issue by naseeresmael** [jiny2001/dcscn-super-resolution#2]
Hi @jiny2001 , thank you very much for this amazing work,  could you please explan to me how to get 2x scale for my own photo, iam very sorry for wasteing your time 😊😊

**Comment by jiny2001** [comment]
Hi, you can use DCSCN.do_for_file() function.
I add sr.py for applying your own image file. Place the file under DCSCN directory and run sr.py like "python sr.py --dataset yang_bsd_4 --file your_image_file.png" and results will be in "output" directory.

**Comment by naseeresmael** [comment]
Thank you @jiny2001 , always willing to help!👏
