### ISSUE TITLE
Issues about convert_rgb_to_ycbcr function

### ISSUE THREAD

**Issue by opteroncx** [jiny2001/dcscn-super-resolution#20]
Hi, your code have some issues with the convert_rgb_to_ycbcr function
https://github.com/jiny2001/dcscn-super-resolution/blob/master/helper/utilty.py#L164-L166

**Comment by opteroncx** [comment]
This should be modified to [65.738 / 256.0, 129.057 / 256.0, 25.064 / 256.0]

**Comment by jiny2001** [comment]
Oh, thx. 
I have implemented with the wiki page https://en.wikipedia.org/wiki/YCbCr. And now I found my code is for analog RGB to digital YCbCr. I'm gonna use digital RGB to digital YCbCr conversion which is as same as your equation. 

I'll update the code tonight. Thank you so much.
