### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#24]
i run train.py from cmd console, but for doing that i have to write "py train.py .... " and i am getting train.py like one more argument for the script. trying to fix it, no clue.

![image](https://user-images.githubusercontent.com/26292862/39267531-b3f7030a-4892-11e8-8f83-ab05e492e49d.png)

**Comment by jiny2001** [comment]
Hi,

I also have happened to met this. In some environment, I think, if the arg is boolean, you don't need to put True or False. 

In that case, change the default value of pixel_shuffler to "False" in the arg list. And then

"train.py --pixel_shuffler" which means, pixel_shuffler is on.
"train.py" which means, pixel_shuffler is off.

I'm not sure why it happens, though...

**Comment by rafariva** [comment]
what if in args.py the "pixel_shuffler" define it like string "True", then in DCSCN.py in line 42 do
self.pixel_shuffler = **bool**(flags.pixel_shuffler)

it works 4 me

**Comment by jiny2001** [comment]
Hi, thank you for the nice hack! 

Your code is nice, however, I want to follow the major way of using args and I found this can be the usual way. Like,

--scale=2 --build_batch=true --pixel_shuffler=false

Could you follow this way?
I'm gonna change my readme doc soon.

**Comment by rafariva** [comment]
looks like you update the train.py 
i havent try it yet, but it looks it shoulds work.
(looking for how to enable use of multiple GPUs, a collegue told me it just one line, looking for that, if i get it, i will tell you.)

tks ur support

**Comment by jiny2001** [comment]
Thanks, please let me know when you have it.
Actually I'm using Geforce 1080Ti2 and I still have one more 1060 which is not used now. I think I can use this to speed up my training. :)
