### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by msiraj83** [jiny2001/dcscn-super-resolution#25]
Hi,

I clone the latest version and try to fin-tuned the old model, but this time i got memory problem. screen shot is attached.
![dscn_fine-tuned-memory_erro](https://user-images.githubusercontent.com/8863047/39659104-62b2b6cc-504b-11e8-8df1-e5d1f20cb1cb.png)

**Comment by jiny2001** [comment]
Hi, I have never seen such a thing.

Since it looks tensorflow can't get enough CPU memory, I believe you're using CPU? The original model with 12 layers and 196 filters maybe bigger than your PC memory.

Could you try training with smaller model?

**Comment by msiraj83** [comment]
Dear @jiny2001 

Thanks yes i reduce the number of layers tp 07.. its remove the first error but it generate another error..How many layer you train the old model ??
![dscn_layers_erro](https://user-images.githubusercontent.com/8863047/39660462-b39adb5a-5069-11e8-8ee2-8217ed77a837.png)

Also i want to write the weights after certain number of epcho like 10..

Thanks

**Comment by jiny2001** [comment]
Hi, the model contained in the github is for 12 layers with 196 filters.

You can't use for different architecture. I mean, you should train again from the scratch for other model parameter.

I can train and upload for smaller model, but I strongly recommend you to use GPU if (layer > 7 || filter > 64), it will be really really slow even if for fine-tuning.

**Comment by jiny2001** [comment]
Hi, I uploaded small (layers=8, filters=96) model. The performance of the model is just 0.1-0.2 dB behind from the default model. Not so different.

You can try with that. :)
