### ISSUE TITLE
Problem training a model

### ISSUE THREAD

**Issue by dgdelahera** [jiny2001/dcscn-super-resolution#27]
I tried to train a new model with different parameters, but I always get the same problem. The Model initialized and then it does not do anything else. Should I wait or is it that I'm doing something wrong? I attach an image at the moment where the program stays.

![imagen](https://user-images.githubusercontent.com/17180389/39988667-407dc8c0-5768-11e8-8b93-8d9df223587c.png)

Thanks for your help!

**Comment by jiny2001** [comment]
Hi,
Is it still in the same status? How long time does it look stopped?

Could you train with small --training_images with small layers/filters parameters?

**Comment by jiny2001** [comment]
I 'm testing with default parameter with dataset=yang91.
And the result is like this

```
Test Data:set5 Training Data:yang91
Total 48 variables, 1,754,942 params
Model initialized.
2018/5/15 1:48:21 Step:1,200 MSE:14.881072 PSNR:37.220988 (Training PSNR:31.641)
Epoch:1 LR:0.002000 (0.262sec/step) Estimated:5:25:23
2018/5/15 1:53:42 Step:2,400 MSE:14.774282 PSNR:37.286557 (Training PSNR:32.704)
Epoch:2 LR:0.002000 (0.265sec/step) Estimated:5:23:24
2018/5/15 1:59:7 Step:3,600 MSE:14.623319 PSNR:37.325265 (Training PSNR:32.838)
Epoch:3 LR:0.002000 (0.267sec/step) Estimated:5:20:12

```
Usually, it takes 8-10min for 1 epoch with my 1080Ti2.
When I'm testing on my CPU, I'll use layers=4, filters=32 and also very small training_imags like < 200.

 Hope those info helps.

**Comment by dgdelahera** [comment]
Okey, now is working! I was testing on CPU so it was a big model for that. I'm testing with layers=4 and filters=32 and everything is working fine. 

Thank you so much and sorry for the inconvenience :)
