### ISSUE TITLE
How to proceed with Decimal Scaling factor?

### ISSUE THREAD

**Issue by mcabinaya** [jiny2001/dcscn-super-resolution#30]
Hi,

First of all thanks for the code. I have a quick question. The paper deals with upscaling the resolution by scale factor of 2 , 3 etc. 
So I can basically upscale 8 * 8 to 16 * 16(scale 2) or 24 * 24 (scale 3) or 32 * 32(scale 4)

How to adopt this techniques to say, if I want to upscale 24 * 24 to 32 * 32 (scale 1.3) , or 28 * 28 to 32 * 32 (scale 1.1)? Is this possible?

**Comment by yu45020** [comment]
Common up-scaling methods are transpose convolution and pixel shuffle, so I don't think it is possible to fractional up-scale images. This applies to architectures that extract features from low resolution images. 

A possible solution is to up-scale an image to 2 and down scale to 1.5, for example, by bicubic. 

Or you may want to change the architecture that upscale image first and then extract features. Such approach is free from scaling factor as input and output images have the same size, but it has heavier computation. 

If you want to do it in this way, I recommend to train images that have different scaling factor, so you may only need to train one model (reference: [vdsr](https://arxiv.org/abs/1511.04587), 4.3 'single model for multiple scales)

**Comment by jiny2001** [comment]
Hi, this is intersting topic.

I agree with yu4020. If you up-sample the images first and then try super resolution, it will work. This would be an easiest way.

In other way, you can use your own up-sampling converter like pixel shuffler. For ex, you can train (28x28)x(input_features)x(32x32)x(output_features) weight_matrix+bias_vector. This is just like learning the mapping from 28x28-LR image into 32x32-HR image.

However, in this case, you must code a function that 1)accepts free size image 2)divide it into multiple 28x28 patches 3) process each patches 4) merge the patches into HR images. You have to think about how you merge the patch boundaries. It might be a little annoying though. :)

**Comment by mcabinaya** [comment]
Thanks for the suggestions guys. Highly appreciate them. I'm just having the issue opened for a few days to see if I can brainstorm some more suggestions.
