### ISSUE TITLE
How can I train my data with 4 GPUs,it seems that only one GPU works during training.Need I change the code?

### ISSUE THREAD

**Issue by wehkjhkl** [jiny2001/dcscn-super-resolution#33]

**Comment by jiny2001** [comment]
I believe you need to modify the code. Assign each computation graph to each GPU like this?
https://www.tensorflow.org/programmers_guide/using_gpu

Thx.

**Comment by wehkjhkl** [comment]
Do you use only one gpu?how long do you train a model with training images=80000?

**Comment by jiny2001** [comment]
Yes, I'm using one 1080 Ti.

In the case of default (12 layers 196 features) parameters with training_images = 120,000 it finished in 25 hours. So I guess in the case of training images=80000, it will finish around 16 - 20 hours.

You can use 8 layers with 96 features or even smaller model. It makes training time much shorter.

**Comment by wehkjhkl** [comment]
thank you!

**Comment by jiny2001** [comment]
Yep!
When you are using GPU, the big part of the computation time is coming from data loading.

If your dataset is enough small, I recommend you to use --bulid_batch=true. Or if your image is color PNG/JPEG and the resolution is bigger than 200 or 400 pixels, it's better to convert to monochrome bmp before training.

Or you can try smaller batch_image_size like 32. it will also reduce training time. Feel free to ask me anything, thx!
