### ISSUE TITLE
empty range for randrange()

### ISSUE THREAD

**Issue by ManoaNosea** [jiny2001/dcscn-super-resolution#34]
```λ python train.py --dataset=set5 --scale=8
Python Interpreter version:3.5
tensorflow version:1.8.0-rc0
numpy version:1.14.2
Session and graph initialized.
2018-06-17 12:38:54.690926: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

DCSCN v2-------------------------------------
2018/6/17 12:38:54 [dcscn_L12_F196to48_Sc8_NIN_A64_PS_R1F32]
Feature:196 166 148 133 120 108 97 86 76 66 57 48  Total: (1301)64 32 32 6144 1  Complexity:6,737,342 Receptive Fields:29
CNN1/conv_W:0 (3, 3, 1, 196)=1764, CNN1/conv_B:0 196, CNN1/prelu/CNN1_prelu:0 196, CNN2/conv_W:0 (3, 3, 196, 166)=292824, CNN2/conv_B:0 166, CNN2/prelu/CNN2_prelu:0 166, CNN3/conv_W:0 (3, 3, 166, 148)=221112, CNN3/conv_B:0 148, CNN3/prelu/CNN3_prelu:0 148, CNN4/conv_W:0 (3, 3, 148, 133)=177156, CNN4/conv_B:0 133, CNN4/prelu/CNN4_prelu:0 133, CNN5/conv_W:0 (3, 3, 133, 120)=143640, CNN5/conv_B:0 120, CNN5/prelu/CNN5_prelu:0 120, CNN6/conv_W:0 (3, 3, 120, 108)=116640, CNN6/conv_B:0 108, CNN6/prelu/CNN6_prelu:0 108, CNN7/conv_W:0 (3, 3, 108, 97)=94284, CNN7/conv_B:0 97, CNN7/prelu/CNN7_prelu:0 97, CNN8/conv_W:0 (3, 3, 97, 86)=75078, CNN8/conv_B:0 86, CNN8/prelu/CNN8_prelu:0 86, CNN9/conv_W:0 (3, 3, 86, 76)=58824, CNN9/conv_B:0 76, CNN9/prelu/CNN9_prelu:0 76, CNN10/conv_W:0 (3, 3, 76, 66)=45144, CNN10/conv_B:0 66, CNN10/prelu/CNN10_prelu:0 66, CNN11/conv_W:0 (3, 3, 66, 57)=33858, CNN11/conv_B:0 57, CNN11/prelu/CNN11_prelu:0 57, CNN12/conv_W:0 (3, 3, 57, 48)=24624, CNN12/conv_B:0 48, CNN12/prelu/CNN12_prelu:0 48, A1/conv_W:0 (1, 1, 1301, 64)=83264, A1/conv_B:0 64, A1/prelu/A1_prelu:0 64, B1/conv_W:0 (1, 1, 1301, 32)=41632, B1/conv_B:0 32, B1/prelu/B1_prelu:0 32, B2/conv_W:0 (3, 3, 32, 32)=9216, B2/conv_B:0 32, B2/prelu/B2_prelu:0 32, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 96, 6144)=5308416, Up-PS/Up-PS_CNN/conv_B:0 6144, R-CNN1/conv_W:0 (3, 3, 96, 1)=864,
Total 48 variables, 6,737,342 params

['train.py', '--dataset=set5', '--scale=8']
Test Data:set5 Training Data:set5
Total 48 variables, 6,737,342 params
Model initialized.
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    tf.app.run()
  File "C:\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 44, in main
    mse = train(model, FLAGS, i)
  File "train.py", line 74, in train
    model.build_input_batch()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-resolution-master\DCSCN.py", line 182, in build_input_batch
    self.batch_input[i], self.batch_input_bicubic[i], self.batch_true[i] = self.train.load_batch_image()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-resolution-master\helper\loader.py", line 309, in load_batch_image
    image = self.load_random_patch(self.filenames[self.get_next_image_no()])
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-resolution-master\helper\loader.py", line 328, in load_random_patch
    x = random.randrange(width - load_batch_size)
  File "C:\Python35\lib\random.py", line 195, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()```
what the problem ?

**Comment by ManoaNosea** [comment]
3.6 same problem:
```Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-resolution-
master>python train.py --dataset=set5 --scale=8
Python Interpreter version:3.6
tensorflow version:1.8.0
numpy version:1.13.3
Session and graph initialized.
2018-06-17 12:42:46.275172: I T:\src\github\tensorflow\tensorflow\core\platform\
cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow bi
nary was not compiled to use: AVX2

DCSCN v2-------------------------------------
2018/6/17 12:42:46 [dcscn_L12_F196to48_Sc8_NIN_A64_PS_R1F32]
Feature:196 166 148 133 120 108 97 86 76 66 57 48  Total: (1301)64 32 32 6144 1
 Complexity:6,737,342 Receptive Fields:29
CNN1/conv_W:0 (3, 3, 1, 196)=1764, CNN1/conv_B:0 196, CNN1/prelu/CNN1_prelu:0 19
6, CNN2/conv_W:0 (3, 3, 196, 166)=292824, CNN2/conv_B:0 166, CNN2/prelu/CNN2_pre
lu:0 166, CNN3/conv_W:0 (3, 3, 166, 148)=221112, CNN3/conv_B:0 148, CNN3/prelu/C
NN3_prelu:0 148, CNN4/conv_W:0 (3, 3, 148, 133)=177156, CNN4/conv_B:0 133, CNN4/
prelu/CNN4_prelu:0 133, CNN5/conv_W:0 (3, 3, 133, 120)=143640, CNN5/conv_B:0 120
, CNN5/prelu/CNN5_prelu:0 120, CNN6/conv_W:0 (3, 3, 120, 108)=116640, CNN6/conv_
B:0 108, CNN6/prelu/CNN6_prelu:0 108, CNN7/conv_W:0 (3, 3, 108, 97)=94284, CNN7/
conv_B:0 97, CNN7/prelu/CNN7_prelu:0 97, CNN8/conv_W:0 (3, 3, 97, 86)=75078, CNN
8/conv_B:0 86, CNN8/prelu/CNN8_prelu:0 86, CNN9/conv_W:0 (3, 3, 86, 76)=58824, C
NN9/conv_B:0 76, CNN9/prelu/CNN9_prelu:0 76, CNN10/conv_W:0 (3, 3, 76, 66)=45144
, CNN10/conv_B:0 66, CNN10/prelu/CNN10_prelu:0 66, CNN11/conv_W:0 (3, 3, 66, 57)
=33858, CNN11/conv_B:0 57, CNN11/prelu/CNN11_prelu:0 57, CNN12/conv_W:0 (3, 3, 5
7, 48)=24624, CNN12/conv_B:0 48, CNN12/prelu/CNN12_prelu:0 48, A1/conv_W:0 (1, 1
, 1301, 64)=83264, A1/conv_B:0 64, A1/prelu/A1_prelu:0 64, B1/conv_W:0 (1, 1, 13
01, 32)=41632, B1/conv_B:0 32, B1/prelu/B1_prelu:0 32, B2/conv_W:0 (3, 3, 32, 32
)=9216, B2/conv_B:0 32, B2/prelu/B2_prelu:0 32, Up-PS/Up-PS_CNN/conv_W:0 (3, 3,
96, 6144)=5308416, Up-PS/Up-PS_CNN/conv_B:0 6144, R-CNN1/conv_W:0 (3, 3, 96, 1)=
864,
Total 48 variables, 6,737,342 params

['train.py', '--dataset=set5', '--scale=8']
Test Data:set5 Training Data:set5
Total 48 variables, 6,737,342 params
Model initialized.
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    tf.app.run()
  File "D:\Programs64\system\WinPython64-3.6.5\python-3.6.5.amd64\lib\site-packa
ges\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 44, in main
    mse = train(model, FLAGS, i)
  File "train.py", line 74, in train
    model.build_input_batch()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-res
olution-master\DCSCN.py", line 182, in build_input_batch
    self.batch_input[i], self.batch_input_bicubic[i], self.batch_true[i] = self.
train.load_batch_image()
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-res
olution-master\helper\loader.py", line 309, in load_batch_image
    image = self.load_random_patch(self.filenames[self.get_next_image_no()])
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\jiny2001\dcscn-super-res
olution-master\helper\loader.py", line 328, in load_random_patch
    x = random.randrange(width - load_batch_size)
  File "D:\Programs64\system\WinPython64-3.6.5\python-3.6.5.amd64\lib\random.py"
, line 189, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()```

**Comment by jiny2001** [comment]
Hi, this is because the scale is 8.

Since I don't think my model is capable for large scale super resolution, scale is only for 2, 3 and 4 for now. Do you really want to try x8?

**Comment by ManoaNosea** [comment]
I wouldn't mind x8 :)
but I tried training with x4 he gived the same error :x
I am training for now with x2
but I would like to train also with x4 for more options

**Comment by jiny2001** [comment]
Hi, I tested the latest training code with --scale=4, but it looks it's working.
Could you send me the sample image you're training from?

Generally, If you train from only one image, the model is the best one for the image.
We may call it "the model overfits to that image". It means, the model is best for the image but instead they will loose their performance for the other general images. Usually, Machine Learning is for predicting the image you have never seen, though. :)

**Comment by jiny2001** [comment]
I think, you are giving too small image for train.
The default batch_image_size = 48, which means training image size should be bigger than 48 * 4 = 192.

In that case, you can set smaller batch_image_size, like 24 or 32. And also you can use smaller number of layers.

I'll add training data checking code and will show you warnings when the training data is not good. Thx!

**Comment by ManoaNosea** [comment]
you meen at least 192 pixels in both dimensions ?

**Comment by jiny2001** [comment]
Yes. You need 192x192 by default parameter. This is because the model is trained by 48x48 patch image.

When you use --batch_image_size=24, the requirement can be 24*4 = 96 pixel size.

I don't think you need default number of iterations. You can have much much smaller number for training. In that case you can change --training_images to something like 100 or 1000. It depends on how much big model you use.

**Comment by ManoaNosea** [comment]
how big model ? im affraid I don't know this terms :x
bigger model better ?

**Comment by jiny2001** [comment]
Big model means like the model which has large number of layers or large number of filters.

Usually bigger model can have better performance. But if the model gets bigger than the specific point, the performance won't increase or even gets worse. It depends training dataset.

The default number of layers and filters of my model are pretty big. You can try --layers=6 or 8 and --filter = 64 or 96.

**Comment by ManoaNosea** [comment]
on this image I am training with --batch_image_size=3 --scale=32 I have MSE 268 and SNR 24 and the numbers not improved for 7 epoch, I don't think it's going to be good. I will try all your suggested numbers and see what happens.
is it possible that MSE and SNR can mutch more significantly improve with more time ? this work is estimated 12 hours so far it's going for 1 hour.

if I am experimenting with --layers --filter and --training_images and --batch_image_size - I can determine by PSNR and MSE if the result is good ?

**Comment by ManoaNosea** [comment]
your work run on numpy and tensorflow, I looked on the internet for how to run this things on GPU because it's many faster but the only option is CUDA and I don't like CUDA, do you know if it possible to run tensorflow numpy/scipy on GPU with OpenCL ?

**Comment by ManoaNosea** [comment]
what I understand so far:
bigger model can help so control him with --filter and --layers
but to make him better you need them to be proportional to --training_images
what would you say is ideal ratio between --training_images and --filter and --layers ?

**Comment by ManoaNosea** [comment]
so far I understand you suggest layer:filter is 1:10
sorry my edit button don't work :x

**Comment by ManoaNosea** [comment]
is there also a relationship between layer:filter:training_images to the sacle ?

**Comment by ManoaNosea** [comment]
is there also a relationship between layer:filter:training_images to the scale ?

**Comment by jiny2001** [comment]
No. There is no straight relations. Including those parameters I mentioned, all other parameters are related and it must be set depend on your dataset or what you want.

You can to try with small numbers and then increase. --batch_image_size=3 --scale=32 won't be work.
Can you make 96x96 images from 3x3 pixels? For my model, scale should be 2 to 4. Thx.

**Comment by ManoaNosea** [comment]
ok I will experiment. how should I consider the MSE and PSNR numbers ? if the numbers are bad does it always meens that the output image will be bad ?
thank, you very help :)

**Comment by jiny2001** [comment]
PSNR or MSE really depends on the image.
My recommendation is comparing with PSNR to existing scaling algorithm. Like bi-cubic or nearest neighbor algorithm. Have fun!

**Comment by ManoaNosea** [comment]
I tried training with several parameters at x4 like the ones you suggested on one image and then upscaling that image but the resulting quality of the image is much worse compared to the pre-trained x4 model, what else should I be trying other than the parameters so far mentioned ?
http://manoa.flnet.org/Pics/pretrainedx4.png
http://manoa.flnet.org/Pics/dcscn_L12_F196to48_Sc4_NIN_A64_PS_R1F32, 31x4, MSE56, SNR30, 200Images.png
http://manoa.flnet.org/Pics/dcscn_L6_F64to48_Sc4_NIN_A64_PS_R1F32, 24x4,MSE63,SNR30,200Images.png

**Comment by jiny2001** [comment]
I feel 6 layers would enough for one image. 12 layers is too much.

Could you give me the URL of GT image you want to try?

**Comment by ManoaNosea** [comment]
this is the original: http://manoa.flnet.org/Pics/a_lfwall16a.png

**Comment by ManoaNosea** [comment]
he is training now
I like the error message, he says not only the problem but also exactly which image have the problem :)

**Comment by jiny2001** [comment]
I believe the error message already contains the filename which has not enough resolution. :)

Thx!!

**Comment by ManoaNosea** [comment]
sory it take so long, I don't have CUDA :x (i whant OpenCL but I don't have it) so 3000 is long time for me.
the result is still very bad compared to the pre trained model

**Comment by jiny2001** [comment]
Take your time!
I'm using 1080Ti, and the training has done in 30 minutes. BTW, I put my trained result here https://github.com/jiny2001/dcscn-super-resolution/tree/master/documents/samples.

So, I guess you want to apply to the GT image and want to get 4x image. right?
In this case, you should use pre-trained data because of the model has not seen the 4x GT data. I was talking about the case to get 4x of 1/4 GT image. In that case, trained by GT image will have the best result. Sorry for confusing you.

**Comment by ManoaNosea** [comment]
im not sure I understand this language :x , I will explain:
I have a 128x256 image, it the only image i have, at first I understood from you that training on that image and then upscaling that same image using the model made from training only on this image - gives the best quality - this is not the case ?

**Comment by jiny2001** [comment]
Sorry, that is not the case.
Training on your image means, training from your 1/4 scale image to true scale image. This 1/4 to 1/1  transformation can learn from your data. I misunderstood you're mentioning this case.

But for the case to get x4 from 1/1 image, it's different. Because you don't know that data.

**Comment by ManoaNosea** [comment]
is training him can help him make better quality at all ? what kind of training would be best for him to make better quality ?

**Comment by jiny2001** [comment]
I don't think training from 1/4 to 1 scale helps making 1 to 4 scale image. It will help only if those mapping has similar transformation.

I believe you have to have 4x images (which you want to generate) for training data. If you have similar images with that 4x images, it will help. Otherwise, No.  The model can't learn what they haven't see.

**Comment by jiny2001** [comment]
I don't think using different model will help.
When you use different model's high resolution image as a GT, my model just learns the different model's way of upscaling. Training data is pair of input and GT image. You need high resolution image as a true data.
