### ISSUE TITLE
Parameters of the c-DCSCN model

### ISSUE THREAD

**Issue by dgdelahera** [jiny2001/dcscn-super-resolution#37]
Hi,

I'm trying to train the c-DCSCN model that is referenced at the paper, but I'm not being able to get the complexity of this model. What parameters should I use to create this model?

Thanks for advance!

**Comment by jiny2001** [comment]
Hi, 
This is nice topic. Thank you.

c-DCSCN was implemented in ver1 branch which is not maintained for now. So now I updated ver2 to capable to represent c-DCSCN. 

Could you update your dcscn project to the latest and then try with these option? I believe these option is equivalent to ver1 c-DCSCN.

--scale=2
--layers=7
--filters=32
--min_filters=8
--filters_decay_gamma=1.2
--nin_filters=24
--nin_filters2=8
--reconstruct_layers=0
--self_ensemble=1
--dataset=yang_bsd_8
--training_images=228688
--batch_image_size=32
--build_batch=True
--do_benchmark=True
--pixel_shuffler_filters=1

I also uploaded sample model for x2 scale. Thx.

**Comment by jiny2001** [comment]
In here, I'm using yang_bsd_8 data. Which is x8 augmentation with (yang91 + BSD200). I believe I was using that data for the paper.

Thx.

**Comment by dgdelahera** [comment]
Hello, 

First of all, I want to thank you for the help and attention. I have tested those parameters and they have worked perfectly. This model runs very well in a cpu.

From my point of view, this compact model is very interesting.  It does not require so many resources and therefore could be implemented in a mobile for example.

Thank you very much for your hard work and effort!
