### ISSUE TITLE
Frozen graph for inference

### ISSUE THREAD

**Issue by phongnhhn92** [jiny2001/dcscn-super-resolution#38]
Hello sirs,
I would like to test your model on mobile device for my own project. In order to do that, i need to convert your ckpt trained files into frozen inference graph (pb format). 
Based on this Tensorflow tutorial [https://www.tensorflow.org/mobile/prepare_models](url), I need to know the input node and output node of your network. Can you help me to do that ? 
Thanks !

**Comment by jiny2001** [comment]
Hi, I had also tried freezing at the other project. I saved the checkpoint and convert it to .pb file and then run it with realtime tensorflow in C++.
Making super resolution model on a phone should be very exciting!

I guess you need the name of input/output tensor, right? However, unfortunately I didn't define a name for output node. I will modify it and update it tonight. thx.

**Comment by phongnhhn92** [comment]
Thanks for your reply !
When I try to read your code, I found this line
https://github.com/jiny2001/dcscn-super-resolution/blob/master/DCSCN.py#L263

I guess you are trying to concat the output of the last 3x3 R-CNN with the bicubic x2 right ?
I will also wait for your fix but I am trying to retrain my model again with a additional line of code:
`self.y_ = self.H[-1] + self.x2`
`self.y_ = tf.idenity(self.y_,"output_tensor")`

Hopefully it works well !

**Comment by jiny2001** [comment]
Yep, you can use tf.identity and also you can do like below if you don't want to add extra graph.
self.y_ = tf.add(self.H[-1], self.x2, name="output_tensor")

Or, you can extract self.H[-1] and add x2 outside of tensorflow. I believe it's better since you can avoid copying to graph or you can parallelize the bi-cubic computation.

Whatever, input "x" has [num_images x input_image_size x input_image_size x 1] shape.
if you use "x2", x2 is a bi-cubic upsampled image.
"output_tensor" has same shape as x2.

Please let me know when you succeed to make it work on the phone!

**Comment by jiny2001** [comment]
Hi, I uploaded compact model for x3 and x4 in case you need it.
I will close this ticket but please feel free to ask anything. thx!

**Comment by phongnhhn92** [comment]
Thanks for your quick fix. 
I am trying to port your trained model to the DLC format which is optimized for the Snapdragon AI processor.
As I said before, I need to convert the trained model from CKPT to PB format. However, as I checked from your DCSCN version 2, your trained models in the models folder dont include the meta file which is available in the version 1. I am using this script to convert from CKPT to PB format.
https://www.dropbox.com/s/v55nw5usqaimkvv/export.py?dl=0
I hope if you have time, can u help me to take a look into this. My code above needs a meta file to build the graph.

**Comment by jiny2001** [comment]
Oh, do we need .meta file also?
Sorry I had tried the freeze_graph() before but I forget it. I uploaded .meta file. Could you try with that?

**Comment by phongnhhn92** [comment]
Yeah, the meta file works for me. I can use the frozen model now but still i am having issues with converting the frozen graph to the mobile device. I am using Snapdragin neural engine api to convert that one to the optimizied model for Snapdragon but so far I didnt have good results. The problem I found is that in your build_graph() function you include the dropout as a unknown shape Tensor. This causes a conflict with the SNPE since it requires all the tensor to have a define shaped. May I ask why u have to include that drop out rate as a placeholder, because this is the first time I see that in practice. Is that possible to build the graph without it since it see you define it as 1.0 everywhere.

**Comment by jiny2001** [comment]
I turn on drop out while training, and turn off during testing.
So placeholder would get 0.8 or something for training and get 1.0 for testing/inference.

I don't know the other way of enabling/disabling drop out. I believe it's possible to create model without dropout (in my code, use --dropout_rate=1.0 to build without dropout) and then load the model trained with dropout. Because dropout doesn't have variable. Could you try that?

**Comment by GengDavid** [comment]
Hi, @phongnhhn92 
I also want to test this model on mobile devices. Have you solve the issue? 
And could you share some of running time on your device? I found that the compact model runs at about 0.4s for 256x256 image(scale=2x), how about the running time on mobile devices? 
Thx!

**Comment by jiny2001** [comment]
Hi @phongnhhn92 and @GengDavid,

I have tested with tensorflow but it looked like tensorflow was so slow comparing to caffe??

I'm also interested in implementation in mobile. If you have any progress and share it with us, it will be really nice!!

Best,

**Comment by phongnhhn92** [comment]
@jiny2001 @GengDavid Hello guys,
I fixed the unknown shape dropout Tensor but now there is another problem since you use some python function to create x2 (bicubic interpolation). What i mean is that you didnt create "x2" as a part of the computation graph. Therefore, during the inference time, I have to manually create a tensor "x2" as the input to the graph. I believe there are 2 solutions for this:
1. Manually create a tensor "x2" and use it as the 2nd input along with the original image tensor "x".
2. Change the code inside build_graph() function so that the tensor "x2" is created using the tensorflow function. [https://www.tensorflow.org/api_docs/python/tf/image/resize_bicubic](url)
Right now, I am working on the 1st approach since it may not require to perform training again. But 2nd approach might be a better solution.
I hope to hear your opinion about this.

**Comment by jiny2001** [comment]
Oh, I see.
I believe 2) is better. If you do that before the graph, It will consume a little time. If you do that inside of the graph, you can make it parallel. And it should not be difficult to implement since tensorflow has bicubic function.

Why I do like 1) in my code is, because I want to store the bicubic image in memory/file to reduce training time, not for saving calculation time. 

I will also play with something on my weekend. Thx!

**Comment by dgdelahera** [comment]
Hi guys

I'm trying to test the compact on mobile devices too. I'm using the snpe-tensorflow-to-dlc script to convert the model to DLC format. I'm having a problem with the R-CNN1 layer, since this layer doesn't have biases and the converter requires that all layers have biases. 

Has anyone managed to solve this error?

Thanks in advance

**Comment by jiny2001** [comment]
Hi, sorry I still have no time to try bicubic upsampling in tensorflow network.

Hi dgdelahera, I believe you can just add bias layer to the last CNN. You can add use_bias=True option at last build_conv() in DCSCN.build_graph(). The line is like below.

self.build_conv("R-CNN%d" % self.reconstruct_layers, self.H[-1], self.cnn_size, input_channels, self.output_channels, use_bias=True)

In this case you need to train again to build a new model file, however, I believe training compact model doesn't take much time. It might be 4-6 hours with gtx1070 or 1080.

**Comment by phongnhhn92** [comment]
I finally fixed all problems( add bias,remove dropout) and successfully convert trained model to SNPE.
The total inference time is about 43ms/img. I am testing ver1 of DCSCN.

**Comment by jiny2001** [comment]
Wow, that's fantastic! Can I ask something more??

What is the size of your image? Is that an average of some dataset like set5 or set14?
Can be much faster when you replace prelu with relu? Because of the implementation of prelu is tricky in tensorflow, I expect it a lot of improvements.

**Comment by GengDavid** [comment]
@phongnhhn92 Wow, That's great!
I'm also interesting in the size of your image. And could you share something more about how to do that? I'm trying to use TensorFlow ```optimize_for_inference``` to remove dropout in frozen graph, but it seems that it does not work.

**Comment by phongnhhn92** [comment]
@jiny2001 
My image size is 80x80 and the ouput is 240x240. I trained x3 model version that you added not long ago.
I calculated the average processing by testing about 20 images. I did more tests this afternoon on total set5 and I receive almost the same number (approximately 43 ms). 

I think you can try implementing prelu like this. I tried this on another project and it works:

def parametric_relu(_x):
  alphas = tf.get_variable('alpha', _x.get_shape()[-1],
                       initializer=tf.constant_initializer(0.0),
                        dtype=tf.float32)
  pos = tf.nn.relu(_x)
  neg = alphas * (_x - abs(_x)) * 0.5

  return pos + neg

**Comment by dgdelahera** [comment]
@jiny2001 @phongnhhn92

I posted the problem with the bias in the [Qualcomm forum](https://developer.qualcomm.com/forum/qdn-forums/software/qualcomm-neural-processing-sdk/36057#comment-15200) and they gave me a solution without needing to retrain the model with bias. Changing a line of the code of the converter I successfully convert the model to .DLC

Hope it helps

**Comment by jiny2001** [comment]
You guys are awesome!!

@phongnhhn92
Can you try the model if I trained without prelu? I did exactly same way as you posted, but I feel that is tricky. And it makes slow since there are unnecessary computations. And I believe relu will have enough performance for compact model.

@dgdelahera 
This is also nice!! Thank you to share with us, I wanna to try later.

**Comment by dgdelahera** [comment]
Hi guys,

I doubt between two ways of develop the app:

1) Use an image in RGB format as input and use tensorflow ops to get the Y channel

2) Convert the image in the app previously and use the Y channel of an image as input

What do you think is the best approach?

Thanks in advance

**Comment by GengDavid** [comment]
Hi, @dgdelahera 
I think it depends on the type of your app. For app that needs to transform all the images, I think [2] is a better choice. But if your want your user to chose witch image to be transform, [1] can save more memory and computation.

**Comment by GengDavid** [comment]
@phongnhhn92 @dgdelahera 
I meet another problem. Could you share about how do you use pixel_shuffler in mobile devices? I just find that I cannot use neither depth_to_space nor transpose_convolution in tflite. Do you implement it by yourself?

**Comment by jiny2001** [comment]
Hi @dgdelahera, I agree with @GengDavid .
I feel 2) would be easier too. However, converting RGB to Y is like a matrix multiply operation so it might be faster if they can use GPU in mobile.

Whatever, if I were you, I will just implement 2) first and if it's not good, will move to 1) as a plan B. :)

**Comment by dgdelahera** [comment]
@jiny2001 @GengDavid 
Okey, I will try this way, thanks for the help!

@GengDavid 
I don't use tflite because this format doesn't support many operations. You can try to freeze the graph and then convert to .DLC format if your mobile has a SnapDragon processor.

**Comment by GengDavid** [comment]
@phongnhhn92 Thanks，I now have a mobile phone with SnapDragon processor, I will try it.

**Comment by dgdelahera** [comment]
Hi guys,

How are your projects going? I hope everything is good!

I have created an app using TensorFlowInferenceInterface to run the model, but I'm having an error when making an inference on the phone:

`No OpKernel was registered to support Op 'ResizeBicubic' with these attrs.`

I have chosen the solution proposed by @phongnhhn92 

> Change the code inside build_graph() function so that the tensor "x2" is created using the tensorflow function. https://www.tensorflow.org/api_docs/python/tf/image/resize_bicubic

My graph is the following:
![model_compact](https://user-images.githubusercontent.com/17180389/43897650-06767c08-9bdd-11e8-9eac-62ee75aee5ec.png)


I do not know if I'm doing something wrong or if that Op is not available on android yet. Does anyone know anything about this?

@phongnhhn92 How did you solve this?



Thanks in advance :)

**Comment by phongnhhn92** [comment]
To be clarify, i choose to use version 1 over version 2 due to the limited number of supported layers by SNPE. I think if you guys want real time inference of version 2 then u guys need to implement unsupported layers of Pixel Suffer in the SNPE library. It requires some knowledge related to writing custom ops which I am not familiar at this moment so until now selecting version for mobile app is my recommended choice.

About the ResizeBicubic ops missing problem, i guess you are trying to run Tensorflow graph on android device right ? I guess the way you build the tensorflow library for Android environment is having some mistake (old tensorflow source version or not built properly,...) However, I doubt the way that u built the whole tf library which is very big and load it into mobile device may cause a very large app and low inference time. I suggest you use snpe which I have been successfully done in my previous attempts.

**Comment by dgdelahera** [comment]
Okey, I will try ver1 then. It is the first time I’m using tf on mobile so probably I’m doing many mistakes :D

Thank you so much for the help!

**Comment by GengDavid** [comment]
@dgdelahera I have tried to use TensorFlowInferenceInterface on Android. Instead of using ```ResizeBicubic`` op, I implemented bicubic function in java so that I didn't need to change the codes of ver2.
However, it seems TensorFlowInferenceInterface does not meet my time requirement.  It runs at around 410ms on Google Pixel 2 for 256*256 to scale up 2 times. 
How about the time for 256*256 images to scale up 2 times on SNPE in your experiments?

**Comment by phongnhhn92** [comment]
In my case it’s about 43ms for version 1, scaling up from 160x160 to 480x480 and i am not using the compact version. I believe if i use compact version and x2 scale then the processing time is much lower.

**Comment by GengDavid** [comment]
I see, thanks. Unsupported ops seems a big problem since I'm also not familiar with embedding custom ops into the framework.  But we still can have a try.

**Comment by GengDavid** [comment]
Hi, @dgdelahera How's it going? Have you successfully built your app using TensorFlowInferenceInterface? I met a very strange problem that TensorFlowInferenceInterface output very different results on some images from which output on PC TensorFlow. Have you met this in your experiment? 
I'm very confusing about this since the input is almost the same(I've checked it carefully) but got totally different ouputs, and the visualized results look terrible for some images.

**Comment by dgdelahera** [comment]
Hi @GengDavid 

Yes, I succesfully build an app using TensorFlowInferenceInterface. My outputs are different from the output on pc too, but I evaluated the output checking the PSNR value and the results appears to be good. At the moment I am only working with 1 channel (Black and White images).

**Comment by GengDavid** [comment]
@dgdelahera Thanks! I'm also only working with Y channel. 
Have you tried to input a image that is not square on mobile devices? I found that if the input image is a square image(such as 256\*256), it performs well. But if I input a rectangle image(such as 256\*510), the output contains some artifact(something like horizontal lines on it). However, this situation does not occur on PC.

**Comment by dgdelahera** [comment]
@GengDavid Actually, I’m only working with square images (500*500). I will try in the following weeks with other inputs. I will post it when I get results :)

**Comment by GengDavid** [comment]
Hi @dgdelahera, I tried the solution you posted on the Qualcomm forum, and that solved the the missing bias error but lead to another error:

```
 - ERROR - Encountered Error: Layer R-CNN1/R-CNN1_conv: convolutional bias should have 1 dimension
Traceback (most recent call last):
  File "/home/zgw/Documents/snpe-1.18.0/bin/x86_64-linux-clang/snpe-tensorflow-to-dlc", line 103, in main
    converter.convert(args.dlc, args.model_version, converter_command)
  File "/home/zgw/Documents/snpe-1.18.0/lib/python/converters/tensorflow/converter.py", line 293, in convert
    self._convert_layers()
  File "/home/zgw/Documents/snpe-1.18.0/lib/python/converters/tensorflow/converter.py", line 340, in _convert_layers
    self._create_layers(descriptors)
  File "/home/zgw/Documents/snpe-1.18.0/lib/python/converters/tensorflow/converter.py", line 376, in _create_layers
    self._create_layer(layer_builder, descriptor)
  File "/home/zgw/Documents/snpe-1.18.0/lib/python/converters/tensorflow/converter.py", line 475, in _create_layer
    layer_builder.build_layer(self._context, descriptor, inputs, outputs)
  File "/home/zgw/Documents/snpe-1.18.0/lib/python/converters/tensorflow/layers/convolution.py", line 361, in build_layer
    groups=descriptor.groups)
ValueError: Layer R-CNN1/R-CNN1_conv: convolutional bias should have 1 dimension
```

Have you met this before? Maybe it still needs to train the model again with bias in convolution layers.
