### ISSUE TITLE
Add document about implement Network in Network

### ISSUE THREAD

**Issue by harrytruong0804** [jiny2001/dcscn-super-resolution#40]
I am training model using your implemented code ver1. I tried to read your implementation code of the Network in Network (NIN) component and found that you used just convolution 2d component. I know this is not an issue but can you explain your implementation of Network in Network?

One more thing, I found that the shape of the output of the scaled image is weird. For example, if the input image shape is [H, W] then the output shape of 3 times scale is [H, W, scale*scale] = [H, W, 9] instead of [H*3, W*3]. What reason you did that? does it your trick to implement the NIN? do you have any document about this implementation?

**Comment by jiny2001** [comment]
Hi, I believe the detail explanation is in my paper.
NIN is a combination of parallel CNNs. What is your exact question? I believe I'm using typical structure.

For the question about outputting 9 channels for scale of 3, this is one of the trick to compute efficiently. Our goal is input W x H cells and output (3 x W) x (3 x H) cells. CNN can't use different W and H for input and output, however, it can use different input/output nodes. So we output 3x3 nodes and map it to 3x3 cells after. Later I found the other guy implemented it in the network and now that is well known as Pixel Shuffler.
