### ISSUE TITLE
Result PSNR

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#45]
Hi

you have a section where you show the different values of PSNR comparing. is there a way to modify evaluation.py to do this, and compare my model with my dataset vs bicubic?

![image](https://user-images.githubusercontent.com/26292862/43528451-a22f6e90-956e-11e8-82ec-64e64bf8cf3c.png)

**Comment by jiny2001** [comment]
I believe, you can just do bicubic up sample instead of doing super resolution in my evaluation.py?

**Comment by jiny2001** [comment]
Hi,
now my code has a evaluation procedure for bi-cubic as well. Run evaluate.py with --compute_bicubic=true. Thx!

**Comment by rafariva** [comment]
Hi, thanks, maybe adding this param (compute_bicubic) on args.py file as default True?

**Comment by jiny2001** [comment]
No, I put the arg in the evaluation.py.
Because you don't need to check bi-cubic performance while on the training, I set the parameter only for evaluating.

**Comment by rafariva** [comment]
your are right.. thanks again
