### ISSUE TITLE
self_ensemble

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#47]
hi, i dont understand what self_ensemble does...? [1..8]??
what 1 means, what 8 does?

**Comment by jiny2001** [comment]
Well, you can read the original paper which I'm referring on the readme.

If I explain ti shortly, 1 means do nothing. 8 means, make 7 more right-left or upside-down flipped images like data augmentation, and then get 8 super resolution images from each augmented inputs. Finally you get only 1 output from averaging those 8 images.

Doing this, you can have averaged result which will mitigate the outlier.

**Comment by rafariva** [comment]
mmm but if i do to my original dataset a dataaumentation x8, in the training will do it again 8x for the batchas?? that is not overfeeting?
(sorry no really understand the differences)

**Comment by jiny2001** [comment]
No,
Self ensemble will be applied only in inference phase. Not happen in training.
So you can use both augmentation and self ensemble at a same time.
