### ISSUE TITLE
Error when training with scale 3 and scale 4

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/dcscn-super-resolution#5]
I can train with:
$ python -u train.py --dataset yang91 --layers 10 --filters 196 --min_filters 48 --filters_decay_gamma 1.2 --last_cnn_size 3 --scale 2

but when I change --scale to 3 or 4, it causes error, **it seem that the image is too small to patch**?

`
Loaded [data/yang91/t2.bmp]: 172 x 179 x 3
Saved [batch_data/yang91/input/000086.bmp]
Saved [batch_data/yang91/interpolated/000086.bmp]
Saved [batch_data/yang91/true/000086.bmp]
Saved [batch_data/yang91/input/000087.bmp]
Saved [batch_data/yang91/interpolated/000087.bmp]
Saved [batch_data/yang91/true/000087.bmp]
Saved [batch_data/yang91/input/000088.bmp]
Saved [batch_data/yang91/interpolated/000088.bmp]
Saved [batch_data/yang91/true/000088.bmp]
Saved [batch_data/yang91/input/000089.bmp]
Saved [batch_data/yang91/interpolated/000089.bmp]
Saved [batch_data/yang91/true/000089.bmp]
Saved [batch_data/yang91/input/000090.bmp]
Saved [batch_data/yang91/interpolated/000090.bmp]
Saved [batch_data/yang91/true/000090.bmp]
Saved [batch_data/yang91/input/000091.bmp]
Saved [batch_data/yang91/interpolated/000091.bmp]
Saved [batch_data/yang91/true/000091.bmp]
Saved [batch_data/yang91/input/000092.bmp]
Saved [batch_data/yang91/interpolated/000092.bmp]
Saved [batch_data/yang91/true/000092.bmp]
Saved [batch_data/yang91/input/000093.bmp]
Saved [batch_data/yang91/interpolated/000093.bmp]
Saved [batch_data/yang91/true/000093.bmp]
Loaded [data/yang91/t20.bmp]: 78 x 78 x 3
Traceback (most recent call last):
  File "train.py", line 113, in <module>
    tf.app.run()
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 30, in main
    FLAGS.batch_image_size, FLAGS.stride_size)
  File "/data1/xxx/cv/dcscn-super-resolution/DCSCN.py", line 160, in load_datasets
    datasets.build_batch(data_dir, batch_dir)
  File "/data1/xxx/cv/dcscn-super-resolution/helper/loader.py", line 185, in build_batch
    input_count = input_batch_images.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by jiny2001** [comment]
Oops, thanks. You are right.
I'm now currently working on the other duplicated code and I know how to solve this issue.
I'll commit the solution later. Wait a little.

**Comment by jiny2001** [comment]
Hi I updated the loader to ignore the input data when it is too small. 

BTW, in x3 or x4 training, Yang91 is not a good dataset in this reason. You can add other larger dataset like BSD200 or General100. Hope your experiments get well.

**Comment by GabrielLin** [comment]
You are very helpful. Now I train it successfully. Thanks for your suggestions.
