### ISSUE TITLE
python3 evaluate.py --test_dataset=set14 --save_results=true

### ISSUE THREAD

**Issue by jingnanopt** [jiny2001/dcscn-super-resolution#51]
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Python Interpreter version:3.5
tensorflow version:1.0.0
numpy version:1.15.0
Session and graph initialized.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

DCSCN v2-------------------------------------
2018/8/22 16:52:39 [dcscn_L12_F196to48_NIN_A64_PS_R1F32]
Traceback (most recent call last):
  File "evaluate.py", line 78, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "evaluate.py", line 46, in main
    model.build_graph()
  File "/home/jing/examples/dcscn-super-resolution-master/DCSCN.py", line 212, in build_graph
    use_batch_norm=self.batch_norm, dropout_rate=self.dropout_rate)
  File "/home/jing/examples/dcscn-super-resolution-master/helper/tf_graph.py", line 126, in build_conv
    h = self.conv2d(input_tensor, w, self.cnn_stride, bias=b, use_batch_norm=use_batch_norm, name=name)
  File "/home/jing/examples/dcscn-super-resolution-master/helper/tf_graph.py", line 107, in conv2d
    self.complexity += self.pix_per_input * int(w.shape[0] * w.shape[1] * w.shape[2] * w.shape[3])
AttributeError: 'Variable' object has no attribute 'shape'

**Comment by jiny2001** [comment]
Hi, thank you to let me know. But it works well on my computers.
Since you're using 1.0.0, could you try somewhat later version of tensorflow? how about 1.4.0 or above?

**Comment by jiny2001** [comment]
I got same error when I use tensorflow 1.0.0. And when I upgraded it into 1.1.0, the error disappeared.
Please use later than 1.1.0. Thank you to let me know. I'll update the readme.
