### ISSUE TITLE
Reconstruction Network and Network in Network

### ISSUE THREAD

**Issue by zisissakel** [jiny2001/dcscn-super-resolution#54]
Hey Jin! You have done an excellent job!! I am trying to figure out what is going on the reconstruction network as regards to the network in network technique. For example, do we have to use a perceptron layer on layers A1, B1, B2? Could you provide me with some insight?
Thank you in advance!

**Comment by jiny2001** [comment]
Hi, I'm not sure what you're asking.
What does "perceptron" mean? A1,B1,B2 contains 1x1 CNN. I feel like it already contains perceptron. Doesn't it??

**Comment by zisissakel** [comment]
Hi! I get what you mean. Thanks for your response!
