### ISSUE TITLE
If validation set gets bigger, it crashes due to lack of resource

### ISSUE THREAD

**Issue by chaos5958** [jiny2001/dcscn-super-resolution#6]
For example, in evaluate(), we run sess over self.x : self.test.input.images.
However, if validation set gets bigger, it quickly run out of memory. 
As in the train step, batch process might mitigate this issue. 
However, I'm not sure summary_op should be also changed or not. 

summary_str, mse = self.sess.run([self.summary_op, self.mse],
			                                 feed_dict={self.x: self.test.input.images,
			                                            self.x2: self.test.input.quad_images,
			                                            self.y: self.test.true.quad_images,
			                                            self.dropout_input: 1.0})

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2394,64,128,128]

**Comment by jiny2001** [comment]
Hi,

Yes, I also got this ResourceExhaustedError sometimes.
How much memory does your GPU has? Currently I use GTX 1080Ti and that kind of problems had gone in my case.

Now the code processes all of the test images at once.
You can let evaluate step to iterate each test images. Or this step is not so important so you can just iterate training step for fixed number of times.

I am very busy these days so it's hard to modify it for now. Sorry.

Best,

Jin

**Comment by chaos5958** [comment]
As you mentioned, it is not critical problem, but could be avoided by step by step evaluations .
Then, I'll close this issue. 
By the way, I sent email to you about DCSCN through email shown in Archive , and I'm looking forward to receive your reply...!

ps. I used GTX titan xp. 

Thank you,
Hyunho

**Comment by XiaotianM** [comment]
Hi, 
    In my opinion, I think the  most important reason is that author has loaded the all training patches in memory which caused the ResourceExhaustedError.
    So, why do not load the training patches in the step of build_batch? It may can ease this problem
