### ISSUE TITLE
is there anyway to get HR without scaling the image?

### ISSUE THREAD

**Issue by bobsfog123** [jiny2001/dcscn-super-resolution#62]
i want to preform the SR on a dataset without scaling it 2,3,4 etc.. is it possible?

**Comment by jiny2001** [comment]
What do you mean "without scaling"?
Do you want to zoom like x1.5 or x20 or any other free scale??

**Comment by AsimSaif001** [comment]
where we go to change scale factor for evaluation ?i con't find for evaluation can you guide me ?

**Comment by jiny2001** [comment]
for evaluating dataset, you can run evaluate.py with --scale==2,3 or 4.
