### ISSUE TITLE
Error 24 too many open files when executing in a loop

### ISSUE THREAD

**Issue by george-viaud** [jiny2001/dcscn-super-resolution#63]
I suspect this is a simple file handle cleanup issues but I'm at a loss as to where to fix it.

Our code triggers `model.do_for_file` in a loop of the files we want to process.  When it reaches the 1001st image, we get the error.  We have many thousands to process.

How would I go about modifying the code so a file handle cleanup can be triggered after each call to `model.do_for_file`?

**Comment by jiny2001** [comment]
Hi, I haven't optimized the function for batch process. However, I believe the do_for_file() function will release all handles and memories. So if you just run that iteratively, there will be no big issue.

Have you tried disable intermediate image file for _bicubic_y or _result_y images?

I'm using scipy.misc.imsave for saving image. I'm sure that function is not suspicious. But you can try different image save module if you still have a problem with that resource error.
