### ISSUE TITLE
About Training Time.

### ISSUE THREAD

**Issue by kikiki1121** [jiny2001/dcscn-super-resolution#66]
Are you using GPU by default?
training_images = 24000
↓
training_images = 100000
I am changing and learning as above, but it will take a lot of time.
It takes about a month?

**Comment by jiny2001** [comment]
Using GPU is kind a default to me. training_images as 150,000 will take 1-2days in my environment.

But I'm sure that 20,000 will work in most of the case. It would be better for CPU. :)

**Comment by kikiki1121** [comment]
About 1 month has passed since I started learning at 10000, but I have not finished yet.
What is the cause?

**Comment by jiny2001** [comment]
taking 1 month only for 10,000 images?? Something would be wrong in this case. How many epochs have you done so far?

The other, most time consuming part is loading/converting training images. For ex, If you use DIV2K without converting monochrome bmp, you need to load from drive and uncompress big (2k x 1k) png and then convert it to YCbCr image each time which will be the major cause. 

Have you checked my readme??

**Comment by kikiki1121** [comment]
I had a misunderstanding.
Should I convert using convert_y.py?

**Comment by jiny2001** [comment]
Hi,
If you're using high resolution image, I believe you should try.
If the images are small, pleas try build_batch option to store every images in memory.

Anyway, there will be a message when the first epoch finished and you can know estimated training time. I recommend you to start with small number of images though. Thx.
