### ISSUE TITLE
About the output result. The output result of the bicubic interpolation is given only in the YCbCr image, but how do you get two kinds of output like DCSCN super resolution results?

### ISSUE THREAD

**Issue by kikiki1121** [jiny2001/dcscn-super-resolution#68]
About the output result.
The output result of the bicubic interpolation is given only in the YCbCr image, but how do you get two kinds of output like DCSCN super resolution results?

**Comment by jiny2001** [comment]
Do you mean the RGB color output of my model?

It will work like this. After it get 1)Y-ch of super res output(HR) image, it will get Cb and Cr channel image from input(LR). And then just use bi-cubic or other upsampling algorithm to get 2)Cb and Cr channel of HR image. Then combine 1) and 2) and convert it into RGB color space.

I can easily expand DCSCN to output HR image for each 3 channels, but I haven't do it since that is a typical way of evaluating SR model performance. Thx.

**Comment by kikiki1121** [comment]
output / modelname / input.png、input_bicubic_y.png、input_result.png、input_result_y.png 

↓

output / modelname / input.png、input_bicubic_y.png、input_bicubic.png，input_result.png、input_result_y.png 


I would like to output as above. Is it possible?

**Comment by kikiki1121** [comment]
output / modelname / input.png、input_bicubic_y.png、input_result.png、input_result_y.png

↓

output / modelname / input.png、input_bicubic_y.png、input_bicubic.png，input_result.png、input_result_y.png

I would like to output as above. Is it possible? How can I change the code?

**Comment by jiny2001** [comment]
Hi,

OK if you want to do that, I guess you can use these lines.

input_image = util.resize_image_by_pil(true_image, 1.0/ self.scale, resampling_method=self.resampling_method)
input_bicubic_image = util.resize_image_by_pil(input_image, self.scale, resampling_method=self.resampling_method)
util.save_image(output_directory + filename + "_input_bicubic" + extension, input_bicubic_image)



Insert those lines after this line (after line 568 in do_for_evaluate_with_output()).
https://github.com/jiny2001/dcscn-super-resolution/blob/master/DCSCN.py#L568

Hope it helps a bit. Thx.

**Comment by kikiki1121** [comment]
"
input_image = util.resize_image_by_pil (true_image, 1.0 / self.scale, resampling_method = self.resampling_method)
                                                                                                            ^
TabError: inconsistent use of tabs and spaces in indentation
"
I get taberror, but do I have to fix everything?

**Comment by kikiki1121** [comment]
I inserted it in the source code.
The obtained output is the same as before
output / modelname / input.png, input_bicubic_y.png, input_result.png, input_result_y.png
In the above four, input_bicubic.png which is the desired output can not be obtained.
What should I do?

**Comment by kikiki1121** [comment]
In the image of the result of bicubic,
Is there a way to eliminate the conversion from RGB to Y?

**Comment by jiny2001** [comment]
OK, I thought you are using evaluation.py to get the  input_bicubic_y.png. Is this correct?
Or are you using sr.py?

**Comment by kikiki1121** [comment]
I used sr.py.
It seems to be solved.

**Comment by jiny2001** [comment]
If you're using sr.py, just add these lines (with proper tabs) into line 545 in DCSCN.py.

scaled_image = util.resize_image_by_pil(org_image, self.scale, resampling_method=self.resampling_method)
util.save_image(output_folder + filename + "_bicubic" + extension, scaled_image)


https://github.com/jiny2001/dcscn-super-resolution/blob/master/DCSCN.py#L544

Thx,

**Comment by kikiki1121** [comment]
Thank you.
It is solved．
