### ISSUE TITLE
About noise removal

### ISSUE THREAD

**Issue by kikiki1121** [jiny2001/dcscn-super-resolution#70]
Has the noise removal component been introduced to the DCSCN model?

**Comment by jiny2001** [comment]
No, noise reduction is a very interesting topic but I haven't tried yet.

**Comment by kikiki1121** [comment]
Thank you. Is it difficult to add noise removal?

**Comment by jiny2001** [comment]
I believe you can try noise reduction in a same manner my DCSCN will have performance for denoising. 

However, the difficult point is how we provide training dataset. It will be OK if you just add noises artificially. But if you want to train with natural images, it would be hard to create ground truth data.

But I agree you can just try any super resolution model with artificial noise as a starting point. Thx.
