### ISSUE TITLE
New Dataset Training with Low Resolution and Original Resolution Images

### ISSUE THREAD

**Issue by hanseungwook** [jiny2001/dcscn-super-resolution#72]
I looked over the code for loading the datasets for the low resolution, low resolution interpolated, and high resolution (ground truth images). It seems like that the low resolution images/dataset is created from the true images by using scaling.

However, would it be possible to load my own low resolution instead of creating them automatically using scaling and resizing?

Would that just require changes in the loader.py for loading the datasets?

**Comment by jiny2001** [comment]
Hi, you have a really good point.

I was thinking to add other upsampling/downsampling method other than bicubic. But unfortunately there is only current bicubic method. 

You're right. The training LR image is created by bicubic from HR source images. There is an option --build_batch=True and when you use it, it will create all training LR batch images before starting training. You may replace that file from yours so in that case you can use your own files.

However, other functions like checking PSNR performance will also use bicubic method. So I'm afraid you must evaluate the performance by yourself. Thx.
