### ISSUE TITLE
[question] regarding to convert_to_multi_channel_image function

### ISSUE THREAD

**Issue by harrytruong0804** [jiny2001/dcscn-super-resolution#73]
I know you use this function to convert the scaled image to multi-channel image which same height and width as the low-resolution image. Say 96x96x1 to 32x32x9. 
You used a function implemented by your self instead of using tf.reshape or np.reshape. Why?

**Comment by jiny2001** [comment]
Hi,
which function do you mean?
Actually I was creating multi channel image by myself in the old previous repo. However, I'm just using tf.depth_to_space() in this repo.

**Comment by harrytruong0804** [comment]
Oh. I mean the function loader.convert_to_multi_channel_image() in version 1. I didn't work with the new repo. 
I tried to replace your implementation of that function by using np.reshape(). However, I could not get a good result compared to your version. 
I am wondering why using np.reshape or tf.reshape cannot get the best result but using your implementation or using tf.deep_to_sapce can get a better result?

**Comment by jiny2001** [comment]
Hi, reshape() doesn't change the order (or sequence) of data. It just change the dimension information of data. But depth_to_space() actually swap some data to map from channels to width - height space. (the actual calculation is inside of the convert_to_multi_channel_image())

However, same conversion is now implemented in tensorflow and there are lots of benefits if you can calculate it inside of the network so I'm just using that for now. :)

**Comment by harrytruong0804** [comment]
OK. Thank you very much for your help.
