### ISSUE TITLE
Training with c-DCSCN missing data/yang_bsd_8/ files

### ISSUE THREAD

**Issue by Meena09** [jiny2001/dcscn-super-resolution#74]
run train.py --scale=2 --layers=7 --filters=32 --min_filters=8 --filters_decay_gamma=1.2 --nin_filters=24 --nin_filters2=8 --reconstruct_layers=0 --self_ensemble=1 --dataset=yang_bsd_8 --training_images=228688 --batch_image_size=32 --build_batch=True --do_benchmark=True --pixel_shuffler_filters=1

While training c-DCSCN, I have executed above line of code on google colaboratory but there is an error  "No such file or directory: 'data/yang_bsd_8/' " from where can I find this data-set ?

**Comment by jiny2001** [comment]
Hi,
You can create that dataset from my repo. yang_bsd_8 means, that is the x8 augmented of yang91 + BSD200.

So I guess you can folllow these to create the dataset. Hope it helps you a bit. Thx.
1)  create yang_bsd directory
2) copy yang91 and bsd200 to that directory
3) use augmentation.py to create x8 data
