### ISSUE TITLE
16 bit Grayscale images

### ISSUE THREAD

**Issue by EscVM** [jiny2001/dcscn-super-resolution#75]
Hi,

First of all, congratulations for the amazing architecture! It's very well done.

I was wondering if there is the possibility to train the network with 16 bit grayscale images. Thanks

**Comment by jiny2001** [comment]
Thx so much!
Actually my network converts integer intensity into 0 to 1 float value to train the model. So basically it's easy IF you have a load/save image function which can treat 16bit png file. However, as far as I searched I couldn't find nice image loader. (and also there was less needs for me)

**Comment by EscVM** [comment]
However, how would it be the output prediction of the network? 16 bit ?

**Comment by jiny2001** [comment]
The network will output from 0 to 1 normalized float value for each pixel. We can just map 0-1 to 0-0xffff value at the output stage.

**Comment by EscVM** [comment]
Thank you so much @jiny2001 for your reply!

So, concretely what and where do I have to change? :)

**Comment by jiny2001** [comment]
Hi, you can check these lines for load and save.
https://github.com/jiny2001/dcscn-super-resolution/blob/master/helper/utilty.py#L239
https://github.com/jiny2001/dcscn-super-resolution/blob/master/helper/utilty.py#L119
