### ISSUE TITLE
Problem loading the pretrained models

### ISSUE THREAD

**Issue by LinkRogers** [jiny2001/dcscn-super-resolution#89]
Hi there,

I tried to load your pretrained model "dcscn_L2_F4to4_PS_R1F4.ckpt.index"

And I typed 
$ python sr.py --file=DVC00046.JPG --layers=2 --filters=4 --min_filters=4 --use_nin=false --reconnstruct_filters=4 

However, I got error:
_

> DCSCN v2-------------------------------------
> 2019/7/11 2:51:11 [dcscn_L2_F4to4_PS_R1F4]
> From /home/vagrant/dcscn/DCSCN.py:188: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> From /home/vagrant/dcscn/helper/utilty.py:424: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.
> 
> From /home/vagrant/dcscn/helper/utilty.py:435: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.
> 
> From /home/vagrant/dcscn/helper/tf_graph.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
> 
> From /home/vagrant/dcscn/helper/utilty.py:355: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.
> 
> From /home/vagrant/dcscn/helper/tf_graph.py:127: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
> Feature:4 4  Total: (8)4 16 1  Complexity:864 Receptive Fields:9
> From /home/vagrant/dcscn/DCSCN.py:329: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.
> 
> From /home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/clip_ops.py:286: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> CNN1/conv_W:0 (3, 3, 1, 4)=36, CNN1/conv_B:0 4, CNN1/prelu/CNN1_prelu:0 4, CNN2/conv_W:0 (3, 3, 4, 4)=144, CNN2/conv_B:0 4, CNN2/prelu/CNN2_prelu:0 4, C/conv_W:0 (1, 1, 8, 4)=32, C/conv_B:0 4, C/prelu/C_prelu:0 4, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 4, 16)=576, Up-PS/Up-PS_CNN/conv_B:0 16, R-CNN1/conv_W:0 (3, 3, 4, 1)=36,
> Total 12 variables, 864 params
> From /home/vagrant/dcscn/helper/tf_graph.py:228: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.
> 
> From /home/vagrant/dcscn/helper/tf_graph.py:229: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.
> 
> From /home/vagrant/dcscn/helper/tf_graph.py:232: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
> 
> 2019-07-11 02:51:14.687490: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
> Model initialized.
> From /home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> 2019-07-11 02:51:15.130103: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key C/conv_B not found in checkpoint
> Traceback (most recent call last):
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
>     return fn(*args)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.NotFoundError: Key C/conv_B not found in checkpoint
>          [[{{node save/RestoreV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
>     run_metadata_ptr)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
>     run_metadata)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Key C/conv_B not found in checkpoint
>          [[node save/RestoreV2 (defined at /home/vagrant/dcscn/helper/tf_graph.py:232) ]]
> 
> Original stack trace for 'save/RestoreV2':
>   File "sr.py", line 51, in <module>
>     tf.app.run()
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "sr.py", line 42, in main
>     model.build_summary_saver()
>   File "/home/vagrant/dcscn/helper/tf_graph.py", line 232, in build_summary_saver
>     self.saver = tf.train.Saver(max_to_keep=None)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
>     self.build()
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
>     build_restore=build_restore)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
>     restore_sequentially, reshape)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
>     restore_sequentially)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
>     name=name)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
>     op_def=op_def)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1296, in restore
>     names_to_keys = object_graph_key_mapping(save_path)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping
>     object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
>     return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
> tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "sr.py", line 51, in <module>
>     tf.app.run()
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "sr.py", line 45, in main
>     model.load_model()
>   File "/home/vagrant/dcscn/helper/tf_graph.py", line 204, in load_model
>     self.saver.restore(self.sess, filename)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
>     err, "a Variable name or other graph key that is missing")
> tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key C/conv_B not found in checkpoint
>          [[node save/RestoreV2 (defined at /home/vagrant/dcscn/helper/tf_graph.py:232) ]]
> 
> Original stack trace for 'save/RestoreV2':
>   File "sr.py", line 51, in <module>
>     tf.app.run()
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "sr.py", line 42, in main
>     model.build_summary_saver()
>   File "/home/vagrant/dcscn/helper/tf_graph.py", line 232, in build_summary_saver
>     self.saver = tf.train.Saver(max_to_keep=None)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
>     self.build()
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
>     build_restore=build_restore)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
>     restore_sequentially, reshape)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
>     restore_sequentially)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
>     name=name)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
>     op_def=op_def)
>   File "/home/vagrant/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
>     self._traceback = tf_stack.extract_stack()

_

Which basically just saying the model loaded does not match the model built.

Plz assist!
TK!

**Comment by jiny2001** [comment]
Interesting, which version of tensorflow are you using? 2.0?

**Comment by LinkRogers** [comment]
> Interesting, which version of tensorflow are you using? 2.0?

Nope. tensorflow '1.14.0'. Is that a problem?

**Comment by jiny2001** [comment]
OK. I'm using 1.13.0 and it worked for me. I see you have typo in your commands.
--reconnstruct_filters=4 has double 'n'.

Could you try "--layers=2 --filters=4 --min_filters=4 --use_nin=false --reconstruct_filters=4"?

**Comment by LinkRogers** [comment]
sry about the typo thing. The actual command I typed in my terminal is correct. Still, it is not working and reporting the same error.

**Comment by jiny2001** [comment]
I see...
Thank you to let me know. It looks the model is not supposed to be published. I mean, it just uploaded by mistake. Could you try the other model? Since only 2 layers doesn't sound work.

**Comment by LinkRogers** [comment]
Yes, I did. It looks like the 4 layers and 7 layers models are bad too. My CPU could not afford to run models larger than 7 layers, so no sure if the other ones would work. However, I tried to train my own 4 layers model but the result does not seem to be promising. The PSNR for my final model is around 36(for 1000 training images). I assume your pretrained model should have much higher scores and perform better?

**Comment by jiny2001** [comment]
Humm.. Now I got the point.

I cloned and tested the 7 layers model and it worked on my CPU version of tensorflow 1.13.1. I don't think 2 layers won't work so I will train 4 layers model and check the performance on this weekend. I'll let you know the results. Thx.

**Comment by jiny2001** [comment]
Hi, sorry for late.
I tried 2 scales for 4 layers model. The result is for set5 dataset. How do you think??

--scale=2 --layers=4 --filters=32 --use_nin=false
PSNR:37.267553, SSIM:0.956839

--scale=4 --layers=4 --filters=32 --use_nin=false
 PSNR:30.911953, SSIM:0.874022
