### ISSUE TITLE
calculate the MSE between the images with the type of float ?

### ISSUE THREAD

**Issue by XiaotianM** [jiny2001/dcscn-super-resolution#9]
I find in your code, you have calculated the mse betweem two images with the type of float.

```
def compute_mse(image1, image2, border_size=0):
	if len(image1.shape) == 2:
		image1 = image1.reshape(image1.shape[0], image1.shape[1], 1)
	if len(image2.shape) == 2:
		image2 = image2.reshape(image2.shape[0], image2.shape[1], 1)

	if image1.shape[0] != image2.shape[0] or image1.shape[1] != image2.shape[1] or image1.shape[2] != image2.shape[2]:
		return None

	if image1.dtype == np.uint8:
		image1 = image1.astype(np.double)
	if image2.dtype == np.uint8:
		image2 = image2.astype(np.double)

	mse = 0.0
	for i in range(border_size, image1.shape[0] - border_size):
		for j in range(border_size, image1.shape[1] - border_size):
			for k in range(image1.shape[2]):
				error = image1[i, j, k] - image2[i, j, k]
				mse += error * error

	return mse / ((image1.shape[0] - 2 * border_size) * (image1.shape[1] - 2 * border_size) * image1.shape[2])
```

However, the psnr should calculated between two images(uint8). 
So, whether it is necessary to convert the result images to "uint8", and then convert them to "double "again to calculate the PSNR or MSE.

**Comment by XiaotianM** [comment]
In SRCNN code: the author has converted the double type to int type to calculate the PSNR

```
%% remove border
im_h = shave(uint8(im_h * 255), [up_scale, up_scale]);
im_gnd = shave(uint8(im_gnd * 255), [up_scale, up_scale]);
im_b = shave(uint8(im_b * 255), [up_scale, up_scale]);

%% compute PSNR
psnr_bic = compute_psnr(im_gnd,im_b);
psnr_srcnn = compute_psnr(im_gnd,im_h);
```

**Comment by jiny2001** [comment]
Hi, thank you for pointing out.

The reason why I converted to double is because I referenced some PSNR calculating code on matlab and they are converting double at the beginning of  the calculation.

Perhaps you are right, however, I'm not confident enough. SRCNN is a good case but is a little old paper. So I'm gonna check other latest code when I have a time.

Or if you suggest me one more latest code. It helps me a lot. :)

**Comment by XiaotianM** [comment]
I just find the LapSRN, the latest method of SR. In their codes:

```
    %% quantize pixel values
    img_GT = im2double(im2uint8(img_GT)); 
    img_HR = im2double(im2uint8(img_HR)); 
```
https://github.com/phoenix104104/LapSRN/blob/master/utils/evaluate_SR.m

If you don't convert to uint8 type for the output of the CNN, the PSNR results will be a litter higher.

**Comment by jiny2001** [comment]
Great! Thank you.

I will change it as like your saying and update soon later.

**Comment by jiny2001** [comment]
Yeah, you are right.

I modified and updated the calculation method of PSNR and I got somewhat low PSNR.

BTW, I was checking NTIRE's PSNR calculation source code on Matlab, and found they are doing like below. Just calculating with double precision. Also it looks images are scaled to 0 - 1.

> if max(F(:)) > 1    
>     F = im2double(F);
> end

I will check their regulations later.
