### ISSUE TITLE
Test on old video images and got little effect...

### ISSUE THREAD

**Issue by LinkRogers** [jiny2001/dcscn-super-resolution#90]

**Comment by LinkRogers** [comment]
Hi, 
I finally got your code to run on GPU and used your default pretrained model(suppose to be the largest one right?). The test image is 640x480 which is from an old video tape. The result SR image looks no difference to the original one. Is this poor domain transfer inevitable? How can I still get some improvement without having to train a large model ? Thanks!

result image
![DVC00047_result](https://user-images.githubusercontent.com/16603615/61105203-c13eec00-a4ab-11e9-8675-191f57c2a666.JPG)

original image
![DVC00047](https://user-images.githubusercontent.com/16603615/61105583-dbc59500-a4ac-11e9-8516-8c5c8ee6342b.JPG)

**Comment by jiny2001** [comment]
Yea, that is because your original image is much blurred (and there also is a degradation from video compressing).
Our model is trained by more clear images.  If you want to have a nice SR performance for that kind of images, you need to train your model for videos.
